version: '2'
services:
  # docker-compose run --rm dev-env
  dev-env:
      build:
        context: docker/nodejs
        dockerfile: Dockerfile
      entrypoint: bash
      environment:
        - AWS_REGION=ap-southeast-2
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
        - AWS_PROFILE
        - AWS_SESSION_TOKEN
        - AWS_SECURITY_TOKEN
        - http_proxy=$HTTP_PROXY
        - https_proxy=$HTTPS_PROXY
      volumes:
        - .:/app
        - ~/.aws:/home/node/.aws
        - ~/.ssh:/home/node/.ssh
